---
- name: Playbook para instalar Cerbot
  hosts: balanceador
  become: yes

  vars_files:
    - /vars/vars.yml
    
  tasks:
    - name: Crear directiva para habilitar AllowOverride
      blockinfile:
        path: /etc/apache2/sites-available/000-default.conf
        block: |
              <Directory "/var/www/html/prestashop">
                AllowOverride ALL
              </Directory>

    - name: Reinicio del servidor Apache
      ansible.builtin.service:
        name: apache2
        state: restarted

    - name: Instalar snap
      command: snap install core

    - name: Actualizar repositorios
      command: snap refresh core
    
    - name: Instalamos cerbot
      snap:
        name: certbot
        state: present
        classic: true
    
    - name: Creamos un usuario para cerbot --------
      ansible.builtin.file:
        src: /snap/bin/certbot
        dest: /usr/bin/certbot
        owner: www-data
        group: www-data
        state: link

    - name: Obtener certificado
      shell: certbot --apache -d {{ DOMINIO_CERBOT }} -m {{ EMAIL }} --agree-tos
      when: install_cerbot == "true"

    - name: Comprobar temporizador para renovacion de certificados -------
      systemd:
        name: list-timers