---
- name: Playbook para instalar WordPress
  hosts: nfs
  become: yes

  tasks:
  - name: Variables
    include_vars:
     ./variables.yml

  - name: Instalar unzip
    apt:
      name: unzip
      state: present

  - name: Descargar WordPress 
    ansible.builtin.get_url:
      url: https://wordpress.org/latest.zip
      dest: /tmp/wordpress.zip

  - name: Descomprimir WordPress en /var/www/html
    ansible.builtin.unarchive:
      src: /tmp/wordpress.zip
      dest: /var/www/html
      remote_src: true

  - name: Copiar archivo de configuración
    copy:
      src: /var/www/html/wordpress/wp-config-sample.php
      dest: /var/www/html/wordpress/wp-config.php
      remote_src: yes

  - name: Configurar variables del archivo de configuración
    replace:
      path: /var/www/html/wordpress/wp-config.php
      regexp: database_name_here
      replace: "{{ DB_NAME }}"

  - name: Configurar variables del archivo de configuración
    replace:
      path: /var/www/html/wordpress/wp-config.php
      regexp: username_here
      replace: "{{ DB_USER }}"

  - name: Configurar variables del archivo de configuración
    replace:
      path: /var/www/html/wordpress/wp-config.php
      regexp: password_here
      replace: "{{ DB_PASS }}"

  - name: Configurar variables del archivo de configuración
    replace:
      path: /var/www/html/wordpress/wp-config.php
      regexp: localhost
      replace: "{{ DB_HOST_PRIVATE_IP }}"


  - name: Copiar archivo index.php de instalación WordPress
    copy:
      src: /var/www/html/wordpress/index.php
      dest: /var/www/html/index.php
      remote_src: yes

  - name: Modificar archivo wp-config.php
    blockinfile:
      path: /var/www/html/wordpress/wp-config.php
      insertafter: DB_COLLATE
      block: |
        define('WP_HOME', '{{ WP_HOME }}');
          define('WP_SITEURL', '{{ WP_SITEURL }}');
          $_SERVER['HTTPS'] = 'on';

  - name: Modificar archivo index.php para redirección a WordPress
    replace:
      path: /var/www/html/index.php
      regexp: wp-blog-header.php
      replace: wordpress/wp-blog-header.php

  - name: Cambiar propietario el directorio /var/www/html
    file:
      path: /var/www/html
      owner: www-data
      group: www-data
      recurse: true
  
  - name: Reiniciar servidor NFS
      ansible.builtin.service:
        name: nfs-kernel-server
        state: restarted
