version: '3.8'

services:
  prestashop:
    image: bitnami/prestashop:8.0.1

    environment:
      - PRESTASHOP_FIRST_NAME=${PRESTASHOP_FIRST_NAME}
      - PRESTASHOP_LAST_NAME=${PRESTASHOP_LAST_NAME}
      - PRESTASHOP_PASSWORD=${PRESTASHOP_PASSWORD}
      - PRESTASHOP_EMAIL=${PRESTASHOP_EMAIL}
      - PRESTASHOP_HOST=${PRESTASHOP_HOST}
      - PRESTASHOP_ENABLE_HTTPS=${PRESTASHOP_ENABLE_HTTPS}
      - PRESTASHOP_COUNTRY=${PRESTASHOP_COUNTRY}
      - PRESTASHOP_LANGUAGE=${PRESTASHOP_LANGUAGE}
      - PRESTASHOP_DATABASE_HOST=mysql
      - PRESTASHOP_DATABASE_NAME=${MYSQL_DATABASE}
      - PRESTASHOP_DATABASE_USER=${MYSQL_USER}
      - PRESTASHOP_DATABASE_PASSWORD=${MYSQL_PASSWORD}
      
    restart: always
    volumes:
      - prestashop_data:/bitnami/prestashop
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - frontend-network
      - backend-network

  mysql:
    image: mysql:8.0
    ports:
       - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: mysql --user=${MYSQL_USER}  --password=${MYSQL_PASSWORD} -e "SHOW DATABASES;"
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - backend-network

  phpmyadmin:
    image: phpmyadmin:5.2.0-apache
    ports:
      - 8080:80
    environment: 
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - frontend-network
      - backend-network

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_certs_data:/var/lib/https-portal
    restart: always
    environment:
      DOMAINS: 'joseasirpresta.hopto.org -> http://prestashop:8080'
      STAGE: 'production'
    restart: always
    networks:
      - frontend-network
    
volumes: 
  mysql_data:
  prestashop_data:
  ssl_certs_data:

networks:
  frontend-network:
  backend-network:
