---
- name: Playbook para descartar una infraestructura basada en Backend - Frontend con grupos de seguridad en Ansible
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:  
    - name:
      include_vars: 
        vars.yml
    
    # Instancia Frontend
    - name: Obtener el ID de la instancia a partir del nombre
      ec2_instance_info:
        filters:
          "tag:Name": '{{ ec2_instance_name_frontend }}' # Busca el nombre de la instancia
          "instance-state-name": "running" # Debe estar encendida
      register: ec2
    
    - name: Desasociar la IP elástica de la instancia Frontend
      ec2_eip:
        device_id: '{{ ec2.instances[0].instance_id }}' # Busca la IP elástica asociada a la instancia
        state: absent # La elimina
    
    - name: Eliminar la instancia EC2
      ec2_instance:
        filters:
          "tag:Name": '{{ ec2_instance_name_frontend }}'
        state: absent
    
    - name: Eliminar el grupo de seguridad
      ec2_group:
        name: '{{ ec2_security_group_frontend }}'
        state: absent
    
    # ------------------------------------------------------------------------------------

    # Instancia Backend

    - name: Obtener el ID de la instancia a partir del nombre
      ec2_instance_info:
        filters:
          "tag:Name": '{{ ec2_instance_name_backend }}'
          "instance-state-name": "running"
      register: ec2

    - name: Eliminar la instancia EC2
      ec2_instance:
        filters:
          "tag:Name": '{{ ec2_instance_name_backend }}'
        state: absent

    - name: Eliminar el grupo de seguridad
      ec2_group:
        name: '{{ ec2_security_group_backend }}'
        state: absent
